BrrrGrrr/urls.py
from django.urls import path
from . import views

app_name = 'BrrrGrrr'

urlpatterns = [
    # Add path here
    path(route='', view=views.homepage_view, name='homepage'),
    path(route='login', view=views.login_view, name='login'),
    path(route='login/', view=views.login_view, name='login'),
    path(route='signup/', view=views.signup_view, name='signup'),
    path(route='signup', view=views.signup_view, name='signup'),
    path(route='orders/', view=views.admin_view, name='orders'),
    path(route='orders', view=views.admin_view, name='orders'),
    path(route='receive_order/', view=views.receive_order, name='receive'),
    path(route='receive_order', view=views.receive_order, name='receive'),
    path(route='new_worker/', view=views.new_Worker_view, name='new'),
    path(route='new_worker', view=views.new_Worker_view, name='new'),
    path(route='logout/', view=views.log_out, name='logout'),
    path(route='logout', view=views.log_out, name='logout'),
    path(route='save/', view=views.save_data, name='save_data'),
    path(route='save', view=views.save_data, name='save_data'),
    path(route='order_complete/', view=views.order_complete, name='order_complete'),
    path(route='order_complete', view=views.order_complete, name='order_complete'),
    path(route='order_history/', view=views.order_history, name='history'),
    path(route='order_history', view=views.order_history, name='history'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BrrrGrrr.urls'))
]

BrrrGrrr/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import ArrayField

# Create your models here.

class Stock(models.Model):
    Materials = models.CharField(max_length=50, unique=True,blank=False)
    Quantity = models.IntegerField()
    Price = models.IntegerField()

class Worker(User):
    Employee_id = models.IntegerField()
    # Phone = models.PhoneNumberField("")

class Order(models.Model):
    order_user = models.IntegerField()
    Time = models.TimeField()
    items = models.JSONField(default=dict)

class Order_History(models.Model):
    order_user = models.CharField(max_length=250, blank=False)  
    Time_Order = models.TimeField()
    Time_finished = models.TimeField()
    items = models.JSONField(default=dict)

BrrrGrrr/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.utils import timezone
from django.contrib.auth.models import User
import json
from django.http import JsonResponse
from .models import *

def get_cost(req_materials):
    material_costs = []
    for item in req_materials:
        stock_item = Stock.objects.get(Materials=item)

        stock_item.Quantity -= 1
        stock_item.save()

        cost = stock_item.Price
        material_costs.append(cost)
    
    return material_costs

def insotck(req_materials):
    instock = True
    for item in req_materials:
        stock_item = Stock.objects.get(Materials=item)
        if(stock_item.Quantity<1):
            instock = False
    return instock


def ordersave(req_materials, user):
    save = False
    user_number = user.id
    current_time = timezone.now().time()
    new_order = Order(order_user=user_number, Time=current_time, items=req_materials)
    new_order.save()
    save = True
    
    return save

def get_username(uid):
    return User.objects.filter(id=uid).first()

# Create your views here.

def homepage_view(request):
    material_data = Stock.objects.filter(Quantity__gt=0)
    user = request.user
    if user.is_authenticated and not user.is_superuser:
        context = {
            'user' : user,
            'material_data': [{'material': item.Materials, 'quantity': item.Quantity, 'price': item.Price} for item in material_data],
        }
    if user.is_authenticated and user.is_superuser:
        return redirect('BrrrGrrr:orders')
    else:
        context = {
            'material_data': [{'material': item.Materials, 'quantity': item.Quantity, 'price': item.Price} for item in material_data],
        }
    return render(request, 'homepage.html', context)

def admin_view(request):
    user = request.user
    if user.is_authenticated and user.is_superuser:
        material_array = Stock.objects.all()
        order_array = Order.objects.all()
        isOldOrder = Order_History.objects.exists()
        context = {
            'material_data': [{'material': item.Materials, 'quantity': item.Quantity, 'price': item.Price} for item in material_array],
            'order_data': [{'Order_Id': item.id, 'Time': item.Time, 'Items': item.items } for item in order_array],
            'isOrderHistory': isOldOrder,
        }
        return render(request, 'admin.html', context)
    else:
        return redirect('BrrrGrrr:login')

def new_Worker_view(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return render(request, 'new_user.html')
    else:
        return redirect('BrrrGrrr:login')

def signup_view(request):
    if request.method == 'POST':
        un = request.POST['username']
        psw = request.POST['pwd']
        email = request.POST['email']
        fn = request.POST['firName']
        ln = request.POST['lasName']
        try:
            user = User.objects.create_user(username=un, email=email, password=psw, first_name = fn, last_name = ln)
            login(request, user)
            return redirect('BrrrGrrr:homepage')
        except Exception as e:
            context={ 'error':f'Error creating account: {e}'}
            return render(request, 'login.html', context)   
    else:
        return render(request, 'login.html')

def login_view(request):
    if request.method == 'POST':
        un = request.POST['username']
        psw = request.POST['pwd']

        user = authenticate(request, username = un, password = psw)

        if user is not None:
            login(request, user)
            if user.is_superuser:
                return redirect('BrrrGrrr:orders')
            else:
                return redirect('BrrrGrrr:homepage')
        else:
            context={
                'error' : 'Invalid Username or Password'
            }
            return render(request, 'login.html', context)
    else:
        return render(request, 'login.html')


def log_out(request):
    logout(request)
    return redirect('BrrrGrrr:homepage')

def save_data(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        materials = data.get('Product')
        quantity = data.get('Quantity')
        price = data.get('Unit_Price')
        print(materials)
        print()
        if(materials is not None and quantity is not None and price is not None):
            existing_stock = Stock.objects.filter(Materials=materials).first()
            if existing_stock:
                # If a record with the same materials exists, update its quantity and price
                existing_stock.Quantity = quantity
                existing_stock.Price = price
                existing_stock.save()
            else:
                # If no record with the same materials exists, create a new Stock record
                Stock.objects.create(Materials=materials, Quantity=quantity, Price=price)
            return JsonResponse({'message': 'Data saved successfully!'})

    return JsonResponse({'error': 'Invalid request method.'}, status=400)

def receive_order(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        if request.method == 'POST':
            data = request.POST.get('selected_materials')
            selected_materials = data.split(',') if data else []
            if(not insotck(selected_materials)):
                return redirect('BrrrGrrr:homepage')
            else:
                if(ordersave(selected_materials, request.user)):
                    price_required = get_cost(selected_materials)
                    materials_with_prices = []
                    for i in range(len(selected_materials)):
                        material_data = {
                            'material': selected_materials[i],
                            'price': price_required[i]
                        }
                        materials_with_prices.append(material_data)
                    context={
                        'user' : request.user,
                        'materials_with_prices' : materials_with_prices,
                    }
                    return render(request, 'Invoice.html', context)
                else:
                    return redirect('BrrrGrrr:homepage')
        else:
            return JsonResponse({'message': 'Invalid request method!'}, status=400)
    else:
        return redirect('BrrrGrrr:login')

def order_complete(request):
    if request.user.is_authenticated and request.user.is_superuser:
        if request.method == 'POST':
            data = json.loads(request.body)
            order_number = data.get('orderId')
            print(request)
            print(order_number)
            try:
                # Get the order details from the Order model
                order = Order.objects.get(pk=order_number)
                # Create a new entry in the Order_History model using the order details
                Order_History.objects.create(
                    order_user=get_username(order.order_user),
                    Time_Order=order.Time,
                    Time_finished=timezone.now(),
                    items=order.items
                )
                # Delete the order entry from the Order model
                order.delete()
                return JsonResponse({'success': True})
            except Order.DoesNotExist:
                # Handle if the order does not exist in the Order model
                return JsonResponse({'success': False, 'message': 'Order not found'}, status=404)
            except Exception as e:
                # Handle other exceptions or errors
                return JsonResponse({'success': False, 'message': str(e)}, status=500)

        return JsonResponse({'success': False, 'message': 'Invalid request method'}, status=400)
    else:
        return redirect('BrrrGrrr:homepage')

def order_history(request):
    if request.user.is_authenticated and request.user.is_superuser:
        Order_History_array = Order_History.objects.all()
        context={
            'Order_history': Order_History_array,
        }
        return render(request, 'history.html', context)
    else:
        return redirect('BrrrGrrr:homepage')

BrrrGrrr/templates/admin.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>BrrrGrrr Orders</title>
    <link rel='stylesheet' type='text/css' href='{% static "BrrrGrrr/css/style.css" %}'>
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css'>
  </head>
  <body class='body'>
    <div class='Logo'>
      <div class='above vertical_lines'>
        <br><br><p>&nbsp;</p><br><p>&nbsp;</p><br><p>&nbsp;</p>
      </div>
    </div>
    <div class='above menu'>
      {% if user.is_authenticated %}
          <input checked='' class='menu_input' id='btn1' name='menu' type='radio' />
          <label class='menu_label' for='btn1'>
              <div class='fa fa-user'></div>
              <div class='menu_text'>
                  {{ user.username }}
              </div>
          </label>
          <input class='menu_input' id='btn2' name='menu' type='radio' />
          <label class='menu_label' for='btn2'>
              <div class='fa fa-sign-out-alt'></div>
              <div class='menu_text'>
                  <a href='{% url 'BrrrGrrr:logout' %}'>Logout</a>
              </div>
          </label>
      {% else %}
          <input checked='' class='menu_input' id='btn1' name='menu' type='radio' />
          <label class='menu_label' for='btn1'>
              <div class='fa fa-sign-in-alt'></div>
              <div class='menu_text'>
                  <a href='{% url 'BrrrGrrr:signup' %}'>Login</a>
              </div>
          </label>
      {% endif %}
    </div>
    <div class='switch-button'>
      <input class='switch-button-checkbox' id='toggle-switch' type='checkbox'>
      <label class='switch-button-label' for=''><span class='switch-button-label-span'>Order</span></label>
    </div>
    <div class='logo'>
      <img src='{% static 'BrrrGrrr/image/logo.png' %}' alt='BrrrGrrr Logo'>
      <h2><b>BRRRGRRR</b></h2>
    </div>
    <div class='part-container'>
      <div id='part-one' class='part active'>
        {% if order_data %}
          <section class='base-cards'>
            {% for item in order_data %}
              <div class='card2' id='{{ item.Order_Id }}'>
                <h3>{{ item.Order_Id }}</h3>
                <table>
                  {% for material in item.Items%}
                    <tr>
                      <td>{{ material }}</td>
                    </tr>
                  {% endfor %}
                </table>
                <button class='complete-order-btn' data-order-id='{{ item.Order_Id }}'>Complete Order</button>
              </div>
            {% endfor %}
          </section>
        {% else %}
          <h2 class="noda"> Sorry No Orders Till Now </h2>
        {% endif %}
        {% if isOrderHistory %}
          <div>
            <button class='button-1'><a href='{% url 'BrrrGrrr:history' %}'>Order History</a></button>
          </div>
        {% endif %}
        <script src='{% static "BrrrGrrr/js/order.js" %}'></script>
      </div>
      <div id='part-two' class='part'>
        <div class='bBox'>
          <div class='newEmployee'><a href='{% url 'BrrrGrrr:new' %}'>Add New Employee</a></div>
        </div>
        <div class='wrapper'>
          {% if material_data %}
            <div class='table'>
              <div class='row header green'>
                <div class='cell'>
                  Product
                </div>
                <div class='cell'>
                  Unit Price
                </div>
                <div class='cell'>
                  Quantity
                </div>
                <div class='cell'>
                  Edit
                </div>
              </div>
              {% for material_data in material_data %}
                <div class='row'>
                  <div class='cell' data-title='Product'>
                    {{ material_data.material }}
                  </div>
                  <div class='cell' data-title='Unit_Price'>
                    ₹{{ material_data.price }}
                  </div>
                  <div class='cell' data-title='Quantity'>
                    {{ material_data.quantity }}
                  </div>
                  <div class='cell' data-title='Edit'>
                    <a href='#' class='edit-link'>Edit</a>
                  </div>
                </div>
              {% endfor %}
            </div>
          {% else %}
            <h2 class='nodata'> Sorry No data Available </h2>
          {% endif %}
          <div>
            {% if material_data %}
              <button id='update-stock-btn' class='button-1'>Add New</button>
              <script src='{% static "BrrrGrrr/js/admin.js" %}'></script>
            {% else %}
              <button id='stock' class='button-1'>Add your first material</button>
              <script src='{% static "BrrrGrrr/js/admin2.js" %}'></script>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

BrrrGrrr/templates/history.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>BrrrGrrr Orders</title>
        <link rel='stylesheet' type='text/css' href='{% static "BrrrGrrr/css/style.css" %}'>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css'>
    </head>
    <body class='body'>
        <div class='Logo'>
            <div class='above vertical_lines'>
                <br><br><p>&nbsp;</p><br><p>&nbsp;</p><br><p>&nbsp;</p>
            </div>
        </div>
        <div class='above menu'>
            {% if user.is_authenticated %}
            <input checked='' class='menu_input' id='btn1' name='menu' type='radio' />
            <label class='menu_label' for='btn1'>
                <div class='fa fa-user'></div>
                <div class='menu_text'>
                    {{ user.username }}
                </div>
            </label>
            <input class='menu_input' id='btn2' name='menu' type='radio' />
            <label class='menu_label' for='btn2'>
                <div class='fa fa-sign-out-alt'></div>
                <div class='menu_text'>
                    <a href='{% url 'BrrrGrrr:logout' %}'>Logout</a>
                </div>
            </label>
            {% else %}
                <input checked='' class='menu_input' id='btn1' name='menu' type='radio' />
                <label class='menu_label' for='btn1'>
                <div class='fa fa-sign-in-alt'></div>
                    <div class='menu_text'>
                        <a href='{% url 'BrrrGrrr:signup' %}'>Login</a>
                    </div>
                </label>
            {% endif %}
        </div>
    <div class='logo'>
        <img src='{% static 'BrrrGrrr/image/logo.png' %}' alt='BrrrGrrr Logo'>
        <h2><b>BRRRGRRR</b></h2>
    </div>
    {% if Order_history %}
        <section class='base-cards'>
            {% for item in Order_history %}
                <div class='card2' id='{{ item.Order_history }}'>
                <h3>{{ item.id }}</h3>
                <h4>{{ item.order_user }}</h4>
                    <table>
                        {% for material in item.items%}
                            <tr>
                                <td>{{ material }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}
        </section>
    {% else %}
        <h2 class="noda"> Sorry No Orders Till Now </h2>
    {% endif %}
    <div>
        <button class='button-1'><a href='{% url 'BrrrGrrr:orders' %}'>Order</a></button>
    </div>
    <script src='{% static "BrrrGrrr/js/order.js" %}'></script>
    </body>
</html>

BrrrGrrr/templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
    <head>
        <title>BrrrGrrr</title>
        <link rel='stylesheet' type='text/css' href='{% static 'BrrrGrrr/css/style.css' %}'>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css'>
    </head>
    <body>
        <div class='topLayer'>
            <div class='above vertical_lines'>
                <br><br><p>&nbsp;</p><br><p>&nbsp;</p><br><p>&nbsp;</p>
            </div>
            <div class='above menu'>
                {% if user.is_authenticated %}
                    <input checked='' class='menu_input' id='btn1' name='menu' type='radio' />
                    <label class='menu_label' for='btn1'>
                        <div class='fa fa-user'></div>
                        <div class='menu_text'>
                            {{ user.username }}
                        </div>
                    </label>
                    <input class='menu_input' id='btn2' name='menu' type='radio' />
                    <label class='menu_label' for='btn2'>
                        <div class='fa fa-sign-out-alt'></div>
                        <div class='menu_text'>
                            <a href='{% url 'BrrrGrrr:logout' %}'>Logout</a>
                        </div>
                    </label>
                {% else %}
                    <input checked='' class='menu_input' id='btn1' name='menu' type='radio' />
                    <label class='menu_label' for='btn1'>
                        <div class='fa fa-sign-in-alt'></div>
                        <div class='menu_text'>
                            <a href='{% url 'BrrrGrrr:signup' %}'>Login</a>
                        </div>
                    </label>
                {% endif %}
            </div>
            <div class='above logo'>
                <img src='{% static 'BrrrGrrr/image/logo.png' %}' alt='BrrrGrrr Logo'>
                <h2><b>BRRRGRRR</b></h2>
            </div>
            <div class='midBox'>
                <img class='content utensil' src='{% static 'BrrrGrrr/image/utensils.png' %}'>
                {% if material_data %}
                    <div class='prices'>
                        <h3>Prices</h3>
                        <table>
                            {% for material_data in material_data %}
                                <tr>
                                    <td>{{ material_data.material }}</td>
                                    <td style='width: 18px;'></td>
                                    <td>₹{{ material_data.price }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                {% endif %}
            </div>
            <div class='lastBox'>
                <img src='{% static 'BrrrGrrr/image/burger.png' %}' class='burger'>
                <div style='display: flex; margin-left: 20%; align-items: flex-end;'>
                    <div class='Stock'>
                        <h3>Ingredients</h3>
                        <table>
                            {% for material_data in material_data|slice:':5' %}
                                <tr>
                                    <td></td><td>{{ material_data.material }}</td><td></td>
                                </tr>
                            {% endfor %}
                            {% if material_data|length > 5 %}
                                <tr>
                                    <td></td><td>Many more...</td><td></td>
                                </tr>
                                <tr></tr>
                            {% endif %}
                            {% if not material_data %}
                                <tr>
                                    <td></td><td>Sorry We're out of stock</td><td></td>
                                </tr>
                                <tr></tr>
                            {% endif %}
                        </table>
                    </div>
                    <div class='BackStock'>
                        {% if material_data|length > 3 %}
                            <p>&nbsp;</p>
                        {% endif %}
                        {% if material_data|length >= 2 %}
                            <p>&nbsp;</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div id='belowLayer'>
            <form id='orderForm' action='{% url 'BrrrGrrr:receive' %}' method='post' class='belowLayer'>
                {% csrf_token  %}
                <div id='materials'>
                    <fieldset class='checkbox-group'>
                        {% if material_data %}
                            <legend class='checkbox-group-legend'>Choose what goes in your burger</legend>
                        {% endif %}
                        {% for material_data in material_data %}
                            <label>
                                <input type='checkbox' class='checkbox-input' data-price='{{ material_data.price }}' name='{{ material_data.material }}'>
                                <span class='checkbox-tile'>
                                    <span class='checkbox-label'>{{ material_data.material }}</span>
                                </span>
                            </label>
                        {% endfor %}
                        {% if not material_data %}
                        <label class='checkbox-label' style='white-space:nowrap; color: blue;'>
                            <p>Sorry We are out of stock</p>
                        </label>
                        {% endif %}
                    </fieldset>
                </div>
                {% if material_data %}
                    <div style='background-color: white; padding: 10px; margin-right: 10%; margin-bottom: auto;'>
                        <div class='BillBox'>
                            <div class='BillBoxInside'>
                                <p>Your Current Order Price is</p>
                                <p style='font-size: large; font-weight: 600;' data-title='Total Price'>₹ 0.00</p>
                                <p>To Pay</p>
                            </div>
                            <button type='submit' class='PayButton'>Pay and recieve order</button>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>
        <script src='{% static 'BrrrGrrr/js/script2.js' %}'></script>
    </body>
</html>

BrrrGrrr/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>BrrrGrrr Orders</title>
    <link rel='stylesheet' type='text/css' href='{% static 'BrrrGrrr/css/style.css' %}'>
  </head>
  <body class='login_page'>
    {% if error %}
    <script>
        alert( '{{error}}' )
    </script>
    {% endif %}
    <div class='main'>
      <input type='checkbox' id='chk' aria-hidden='true'>
      <div class='signup'>
        <form action='{% url 'BrrrGrrr:signup' %}' method='post'>
          {% csrf_token %}
          <label class='label_box' for='chk' aria-hidden='true'>Sign up as User</label>
          <input class='input_box' type='text' name='username' placeholder='User name' required=''>
          <input class='input_box' type='text' name='firName' placeholder='First name' required=''>
          <input class='input_box' type='text' name='lasName' placeholder='Last name' required=''>
          <input class='input_box' type='email' name='email' placeholder='Email' required=''>
          <input class='input_box' type='password' name='pwd' placeholder='Password' required=''>
          <button class='button2' type='submit'>Sign up</button>
        </form>
      </div>

      <div class='login'>
        <form action='{% url 'BrrrGrrr:login' %}' method='post'>
          {% csrf_token %}
          <label class='label_box' for='chk' aria-hidden='true'>Login</label>
          <input class='input_box' type='text' name='username' placeholder='User name' required=''>
          <input class='input_box' type='password' name='pwd' placeholder='Password' required=''>
          <button class='button2' type='submit'>Login</button>
        </form>
      </div>
    </div>
    <script>
      const checkbox = document.getElementById('chk');
      checkbox.checked = true;
    </script>
  </body>
</html>

BrrrGrrr/templates/new_user.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>BrrrGrrr Orders</title>
    <link rel='stylesheet' type='text/css' href='{% static 'BrrrGrrr/css/style.css' %}'>
  </head>
  
<body class='new-form'>
	<div class='form-container'>
		<h3 class='title'>Register</h3>
		<form class='form-horizontal' action='{% url 'BrrrGrrr:new' %}' method='post'>
            <div class='form-group'>
                <label>Name</label>
                <input type='text' class='form-control' placeholder='Name'>
            </div>
            <div class='form-group'>
                <label>Employee Id</label>
                <input type='text' class='form-control' placeholder='Employee Id'>
            </div>
            <div class='form-group'>
                <label>User Name</label>
                <input type='text' class='form-control' placeholder='User Name'>
            </div>
            <div class='form-group'>
                <label>Email ID</label>
                <input type='email' class='form-control' placeholder='Email Address'>
            </div>
            <div class='form-group'>
                <label>Password</label>
                <input type='password' class='form-control' placeholder='Password'>
            </div>
            <div class='form-group'>
                <label>Confirm Password</label>
                <input type='password' class='form-control' placeholder='Confirm Password'>
            </div>
            <h4 class='sub-title'>Personal Information</h4>
            <div class='form-group'>
                <label>Phone No.</label>
                <input type='text' class='form-control' placeholder='Phone Number'>
            </div>
            <div class='form-group'>
                <label>City</label>
                <input type='text' class='form-control' placeholder='City'>
            </div>
			<button class='btn newsignup'>Create Account</button>
		</form>
	</div>
</body>

</html>